{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "da3-dua-web-service-api.serviceAccountName" . }}
  labels:
{{ include "da3-dua-web-service-api.labels" . | indent 4 }}
{{- end -}}
